spring:
  datasource:
    url: jdbc:mysql://mytcatdb.ciatf5mitnm0.ap-northeast-2.rds.amazonaws.com:3306/mytcatdb?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: admin
    password: tcatpro2022
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        #         show_sql: true
        format_sql: true
logging:
  level:
    org.hibernate.SQL: debug
    # org.hibernate.type: trace